### ISSUE TITLE
Powercat doesn't work with files

### ISSUE THREAD

**Issue by mathurin68** [besimorhino/powercat#12]
Was curious if there was bug transferring files, our lab was a windows 7 client(pshell 2.0) going to server 2012(pshell 4) we couldn't get it to transfer files; all other features worked great, got them talking, shells opened, but following the exact instructions(main page) we couldn't get the files to transfer.  
Appreciate any suggestions, and great work on a super cool tool!!

We got ncat working in the same scenario but would really like to have the ability to use powercat as well.

**Comment by secabstraction** [comment]
I'm still testing, and building the payload function, but this is at least 80% working. Testing with ncat. https://github.com/secabstraction/PowerCat

you'll have to go to the working branch for now.
