### ISSUE TITLE
powercat timeout not working?

### ISSUE THREAD

**Issue by tedfulmer** [besimorhino/powercat#14]
I'm trying a powercat with a -t 2 for a two second timeout and seeing 2 minutes. Actually I see two minute timeout regardless of what I set -t 

PS C:\Users\tfulmer> date;powercat -c 10.10.37.111 -p 22 -t 2;date

Thursday, February 23, 2017 3:22:40 PM
SSH-2.0-OpenSSH_7.1
Thursday, February 23, 2017 3:24:40 PM

**Comment by lukebaggett** [comment]
The timeout option means it will give up on _setting up_ the connection after -t seconds. Since you see the SSH banner, the connection was successful and the timeout doesn't apply anymore. If you want to disconnect right after connecting you can use -d.
