### ISSUE TITLE
It is detected now as malware by Windows Defender and 3 of virustotal

### ISSUE THREAD

**Issue by t0nik0** [besimorhino/powercat#18]
https://www.virustotal.com/gui/url/706efd6c741e4562c633433974e2902950b82b2be2c2d794a0acdd10250ef7d1/detection

**Comment by alenros** [comment]
You can resolve this by changing the name of the function:
just edit the file and replace the header
function powercat
with
function powercatt

**Comment by trizzac81** [comment]
It won't if you turn off windows defender, then use the link and then turn it back on.

**Comment by besimorhino** [comment]
Sorry, but the intent of this tool is to not be a defensive evasion system... that said, there are features which help avoid detection.

Future versions will have this more explicitly spelled out.

**Comment by besimorhino** [comment]
Closing this issue. There are methods Powercat has which allows evasion. You can also leverage several different encoding methods and tools to bypass detection. Please consider using them.
