### ISSUE TITLE
Listener Not Remaining Open

### ISSUE THREAD

**Issue by jaypatrick** [besimorhino/powercat#21]
Perhaps I'm misunderstanding how to use this utility, but basically I'm looking for socat like functionality, where I open a listener and it persists, listening for incoming data on the specified port. in socat it would be: `socat TCP-LISTEN:6142,fork stdout`, which in powercat I would think would be `powercat -l -p 6142` however, using this from a PS prompt, the socket is closed as I cannot telnet into it. How do you use this script so that it'll persist?

**Comment by lukebaggett** [comment]
This will make the listener persist: `powercat -l -p 6142 -rep`

**Comment by besimorhino** [comment]
Thanks @lukebaggett !!
