### ISSUE TITLE
Detected on Windows

### ISSUE THREAD

**Issue by Vedant-Bhalgama** [besimorhino/powercat#23]
I Use the powershell command for downloading powercat, It says script contains malicious content

**Comment by besimorhino** [comment]
I'm sorry for any confusion... but the intention of this tool is *not* to evade AMSI.  There are well documented methods for doing so.

In future releases, we may make the capabilities for evading defenses more self evident... (hint: there are existing features which have been leveraged which do work in this manner...)

Currently, it is up to the users of this tool to determine how to evade defensive controls if they wish to do so.

**Comment by jtmoon79** [comment]
This script looks great! Unfortunately several AV vendors flag it https://www.virustotal.com/gui/url/706efd6c741e4562c633433974e2902950b82b2be2c2d794a0acdd10250ef7d1/detection
