### ISSUE TITLE
IEX install with antivirus warning

### ISSUE THREAD

**Issue by vic-t** [besimorhino/powercat#28]
When trying to install PowerCat directly using invoke-expression (IEX), I get the following error in Powershell 7: 

`Invoke-Expression: This script contains malicious content and has been blocked by your antivirus software.`

I'm on Windows 10 with built-in Windows Defender.

**Comment by sunnystew222** [comment]
That's a problem with this tool, even the netcat for windows thingy gets flagged too. Just ignore it.

**Comment by besimorhino** [comment]
Evading AV and other endpoint controls is not something this project is attempting to do.

There are "things" you can do with the code to better evade detection logic.

Sorry to be vague, but you're on your own.
