### ISSUE TITLE
This software looks awesome but misses a LICENSE file.

### ISSUE THREAD

**Issue by ris-work** [besimorhino/powercat#29]
Please add a `LICENSE` with your `copyright notice`, I am interested in using your software for testing. It will become handy because there is _no simple UDP listener that ships with Microsoft Windows (R)_. We always have to write one to test UDP connectivity. Almost all *nix operating systems come with `OpenBSD-netcat` or `netcat-traditional`. Thank you very much.

- Rishikeshan (L/S).

**Comment by besimorhino** [comment]
Good catch. Fixed. Apache 2.0 as was mentioned in some talks we gave around tool release.

Thanks
