### ISSUE TITLE
`IEX: You cannot call a method on a null-valued expression`

### ISSUE THREAD

**Issue by johnjelinek** [besimorhino/powercat#4]
I get the following error if I pipe a message to powercat
```
> 'aaaaa' | powercat -c localhost -p 5514 -u
IEX : You cannot call a method on a null-valued expression.
At \\psf\home\Projects\powercat\powercat.ps1:932 char:18
+       $Output += IEX $InvokeString
+                  ~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Invoke-Expression], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull,Microsoft.PowerShell.Commands.InvokeExpressionCommand
```

**Comment by lukebaggett** [comment]
Thanks for reporting this, we really appreciate it.

![encoding](https://cloud.githubusercontent.com/assets/3998892/8859093/36b85b86-3149-11e5-816d-50ed2b495224.png)

As can be seen in the above screenshot, the $Encoding variable is never declared prior to the highlighted line where it is referenced. Declaring $Encoding in the Main function appears to fix this issue.

Thanks again for your help!

**Comment by johnjelinek** [comment]
:+1:
