### ISSUE TITLE
 powercat -l -p 443 -ep : typing a command in the shell throws an error

### ISSUE THREAD

**Issue by Jeroen1001** [besimorhino/powercat#9]
When trying to connect like so, all goes ok: telnet localhost 443

Then I type the letter d and immediately, I get an error:
[code]
PS H:> dIEX : The term 'd' is not recognized as the name of a cmdlet, function,
 script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:172 char:61
-             try{[byte[]]$ReturnedData = $Encoding.GetBytes((IEX $CommandToExec
  ut ...
-                                                             ~~~~~~~~~~~~~~~~~~
  ~~
  - CategoryInfo          : ObjectNotFound: (d:String) [Invoke-Expression], Co
    mmandNotFoundException
  - FullyQualifiedErrorId : CommandNotFoundException,Microsoft.PowerShell.Commands.InvokeExpressionCommand

PS H:>

Installed PS version:

PS H:> $PSVersionTable.PSVersion

Major  Minor  Build  Revision

---

3      0      -1     -1

Either this is a bug, or I'm doing somthing wrong:)

**Comment by lukebaggett** [comment]
I'm also getting the same issue when using the Microsoft telnet client. Thanks for reporting this bug!

There hasn't been any testing done to verify that the windows telnet client will work with powercat as of yet, so there may be more issues. Testing has been done with GNU netcat, GNU telnet, and Windows netcat, so those may be better options for you in the mean time.

**Comment by Jeroen1001** [comment]
Thank you! Didn't know that:). GNU Telnet works fine. Putty sort of. But GNU Telnet will do nicely!
